import type {
  Destination,
  Friend,
  Memory,
  SelectionList,
  TagCategory,
  Trip,
} from '../types'
import { withTriplessInfrastructure } from '../lib/tripless'
import { cloneDefaultCategories } from '../whimsy/tagLibrary'
import { cloneDefaultSelectionLists } from '../whimsy/selectionLists'

/** Stable ids — safe for “load demo” reset */
const T = {
  spring: 'trip-spring-euro-asia',
  portugal: 'trip-portugal-weekend',
  hokkaido: 'trip-hokkaido-snow',
  nyc: 'trip-nyc-staycation',
  highway: 'trip-pch-slow',
} as const

const D = {
  paris: 'dest-paris',
  tokyo: 'dest-tokyo',
  lisbon: 'dest-lisbon',
  porto: 'dest-porto',
  sapporo: 'dest-sapporo',
  niseko: 'dest-niseko',
  manhattan: 'dest-manhattan',
  brooklyn: 'dest-brooklyn',
  sf: 'dest-sf',
  bigsur: 'dest-bigsur',
  la: 'dest-la',
} as const

const trips: Trip[] = [
  { id: T.spring, name: 'Spring: Paris → Tokyo' },
  { id: T.portugal, name: 'Portugal long weekend' },
  { id: T.hokkaido, name: 'Hokkaido snow week' },
  { id: T.nyc, name: 'NYC staycation' },
  { id: T.highway, name: 'Pacific Coast slow roll' },
]

const destinations: Destination[] = [
  { id: D.paris, tripId: T.spring, name: 'Paris' },
  { id: D.tokyo, tripId: T.spring, name: 'Tokyo' },
  { id: D.lisbon, tripId: T.portugal, name: 'Lisbon' },
  { id: D.porto, tripId: T.portugal, name: 'Porto' },
  { id: D.sapporo, tripId: T.hokkaido, name: 'Sapporo' },
  { id: D.niseko, tripId: T.hokkaido, name: 'Niseko' },
  { id: D.manhattan, tripId: T.nyc, name: 'Manhattan' },
  { id: D.brooklyn, tripId: T.nyc, name: 'Brooklyn' },
  { id: D.sf, tripId: T.highway, name: 'San Francisco' },
  { id: D.bigsur, tripId: T.highway, name: 'Big Sur' },
  { id: D.la, tripId: T.highway, name: 'Los Angeles' },
]

const friends: Friend[] = [
  { id: 'f-alex', name: 'Alex' },
  { id: 'f-sam', name: 'Sam' },
  { id: 'f-morgan', name: 'Morgan' },
  { id: 'f-jules', name: 'Jules' },
]

const memories: Memory[] = [
  /* Spring */
  {
    id: 'm-spring-cdg',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'flight',
    title: 'Landed CDG bleary, happy',
    placeLabel: 'Charles de Gaulle Airport, Paris, France',
    lat: 49.0097,
    lng: 2.5479,
    visitedAt: '2026-03-10T14:00:00.000Z',
    pinEmoji: '✈️',
    countryCode: 'FR',
    adminRegion: 'Île-de-France',
    categoryTags: {
      vibe: ['big city buzz'],
      mood: ['electric'],
      moment: ['first time'],
      activity: ['transit'],
    },
    friendIds: ['f-alex'],
    flightDetails: {
      fromCode: 'JFK',
      toCode: 'CDG',
      fromLat: 40.6413,
      fromLng: -73.7781,
      toLat: 49.0097,
      toLng: 2.5479,
      durationMinutes: 420,
      airline: 'Air France',
      aircraftType: 'B777-300ER',
      cabinClass: 'business',
    },
  },
  {
    id: 'm-spring-bistro',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'restaurant',
    title: 'Bistro night by the river',
    placeLabel: '7th arrondissement, Paris',
    lat: 48.8584,
    lng: 2.2945,
    visitedAt: '2026-03-11T19:30:00.000Z',
    pinEmoji: '🍽️',
    countryCode: 'FR',
    adminRegion: 'Île-de-France',
    categoryTags: {
      vibe: ['golden hour'],
      mood: ['cozy'],
      activity: ['food'],
    },
    friendIds: ['f-alex', 'f-sam'],
    selectionListValues: { cuisine: 'French' },
    restaurantDetails: {
      wouldEatAgain: true,
      rating: 5,
      cuisine: 'French',
      venueStyle: 'Bistro',
    },
    body: 'Steak frites, too much wine, perfect.',
  },
  {
    id: 'm-spring-hotel',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'hotel',
    title: 'Left Bank nest',
    lat: 48.85,
    lng: 2.34,
    visitedAt: '2026-03-11T15:00:00.000Z',
    countryCode: 'FR',
    categoryTags: { mood: ['peaceful'], activity: ['transit'] },
    hotelDetails: {
      checkIn: '2026-03-11',
      checkOut: '2026-03-14',
      nights: 3,
      brand: 'Boutique Left Bank',
    },
  },
  {
    id: 'm-spring-louvre',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'sight',
    title: 'Louvre sprint (failed)',
    placeLabel: 'Musée du Louvre',
    lat: 48.8606,
    lng: 2.3376,
    visitedAt: '2026-03-12T11:00:00.000Z',
    pinEmoji: '🏛️',
    countryCode: 'FR',
    categoryTags: { activity: ['museum'], moment: ['tiny joy'] },
    body: 'Only saw Denon wing. Next time: full day.',
    sightDetails: { venueType: 'Museum' },
  },
  {
    id: 'm-spring-tokyo-flight',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'flight',
    title: 'Overnight hop to Haneda',
    lat: 35.5494,
    lng: 139.7798,
    visitedAt: '2026-03-15T06:30:00.000Z',
    countryCode: 'JP',
    adminRegion: 'Tokyo',
    categoryTags: { vibe: ['big city buzz'], activity: ['transit'] },
    flightDetails: {
      fromCode: 'CDG',
      toCode: 'HND',
      fromLat: 49.0097,
      fromLng: 2.5479,
      toLat: 35.5494,
      toLng: 139.7798,
      durationMinutes: 840,
    },
  },
  {
    id: 'm-spring-ramen',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'restaurant',
    title: 'Ramen counter at midnight',
    placeLabel: 'Shibuya, Tokyo',
    lat: 35.69,
    lng: 139.7,
    visitedAt: '2026-03-16T00:20:00.000Z',
    pinEmoji: '🍜',
    countryCode: 'JP',
    categoryTags: { vibe: ['locals only'], mood: ['giddy'], activity: ['food'] },
    restaurantDetails: { wouldEatAgain: true },
  },
  /* Same calendar day other years — “this time last year” playground */
  {
    id: 'm-echo-2024-0330',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'note',
    title: '2024 — rainy Tuesday notes',
    lat: 38.7223,
    lng: -9.1393,
    visitedAt: '2024-03-30T11:00:00.000Z',
    countryCode: 'PT',
    body: 'Demo: same month & day as other years for the time-machine card.',
  },
  {
    id: 'm-echo-2025-0330',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'note',
    title: '2025 — coffee & deadlines',
    lat: 40.7589,
    lng: -73.9851,
    visitedAt: '2025-03-30T15:30:00.000Z',
    countryCode: 'US',
    adminRegion: 'New York',
    categoryTags: { activity: ['coffee'], mood: ['peaceful'] },
    body: 'Another March 30 for the whimsy panel.',
  },
  {
    id: 'm-echo-2026-0330',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'sight',
    title: '2026 — cherry buds, early',
    lat: 35.7148,
    lng: 139.7967,
    visitedAt: '2026-03-30T08:00:00.000Z',
    countryCode: 'JP',
    pinEmoji: '🌸',
    categoryTags: { moment: ['tiny joy'], vibe: ['golden hour'] },
  },
  /* Portugal */
  {
    id: 'm-ptl-tram',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'sight',
    title: 'Alfama tiles & tram 28',
    placeLabel: 'Alfama, Lisbon',
    lat: 38.7125,
    lng: -9.1333,
    visitedAt: '2025-11-08T10:00:00.000Z',
    countryCode: 'PT',
    adminRegion: 'Lisbon',
    pinEmoji: '🚂',
    categoryTags: { vibe: ['golden hour'], activity: ['transit'] },
    friendIds: ['f-morgan'],
    body: 'Crowded but gorgeous light.',
  },
  {
    id: 'm-ptl-pasteis',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'restaurant',
    title: 'Pastéis emergency',
    lat: 38.6979,
    lng: -9.2034,
    visitedAt: '2025-11-08T08:30:00.000Z',
    countryCode: 'PT',
    categoryTags: { activity: ['food', 'coffee'], mood: ['giddy'] },
    restaurantDetails: { wouldEatAgain: true, rating: 5 },
  },
  {
    id: 'm-ptl-porto',
    tripId: T.portugal,
    destinationId: D.porto,
    kind: 'note',
    title: 'Porto river fog',
    placeLabel: 'Ribeira, Porto',
    lat: 41.14,
    lng: -8.61,
    visitedAt: '2025-11-09T16:00:00.000Z',
    countryCode: 'PT',
    categoryTags: { mood: ['peaceful'], vibe: ['off the map'] },
    body: 'Sat on a wall. Did nothing. 10/10.',
  },
  /* Hokkaido */
  {
    id: 'm-hok-sapporo',
    tripId: T.hokkaido,
    destinationId: D.sapporo,
    kind: 'restaurant',
    title: 'Soup curry recovery meal',
    lat: 43.0618,
    lng: 141.3545,
    visitedAt: '2025-02-03T19:00:00.000Z',
    countryCode: 'JP',
    adminRegion: 'Hokkaido',
    pinEmoji: '🍜',
    categoryTags: { activity: ['food'], mood: ['cozy'] },
    restaurantDetails: { wouldEatAgain: true },
    friendIds: ['f-jules', 'f-sam'],
  },
  {
    id: 'm-hok-niseko',
    tripId: T.hokkaido,
    destinationId: D.niseko,
    kind: 'sight',
    title: 'Niseko powder day',
    lat: 42.8053,
    lng: 140.6876,
    visitedAt: '2025-02-05T09:00:00.000Z',
    pinEmoji: '🎿',
    countryCode: 'JP',
    categoryTags: { activity: ['hike'], moment: ['first time'] },
    body: 'Face shots until legs gave out.',
  },
  /* NYC */
  {
    id: 'm-nyc-bagel',
    tripId: T.nyc,
    destinationId: D.brooklyn,
    kind: 'restaurant',
    title: 'Bagel bench sunrise',
    placeLabel: 'Prospect Park, Brooklyn',
    lat: 40.66,
    lng: -73.97,
    visitedAt: '2025-09-14T06:45:00.000Z',
    countryCode: 'US',
    adminRegion: 'New York',
    pinEmoji: '🥐',
    categoryTags: { vibe: ['golden hour'], activity: ['food', 'coffee'] },
    restaurantDetails: { wouldEatAgain: true },
  },
  {
    id: 'm-nyc-met',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'sight',
    title: 'Met rooftop closed — wandered Greek instead',
    lat: 40.7794,
    lng: -73.9632,
    visitedAt: '2025-09-15T13:00:00.000Z',
    countryCode: 'US',
    adminRegion: 'New York',
    categoryTags: { activity: ['museum'] },
    friendIds: ['f-alex'],
  },
  {
    id: 'm-nyc-hotel',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'hotel',
    title: 'Tiny room, huge windows',
    lat: 40.758,
    lng: -73.9855,
    visitedAt: '2025-09-14T15:00:00.000Z',
    countryCode: 'US',
    hotelDetails: { checkIn: '2025-09-14', checkOut: '2025-09-17' },
  },
  /* PCH */
  {
    id: 'm-pch-sf',
    tripId: T.highway,
    destinationId: D.sf,
    kind: 'restaurant',
    title: 'Four Barrel before the bridge',
    placeLabel: 'Mission, San Francisco',
    lat: 37.767,
    lng: -122.421,
    visitedAt: '2024-10-01T09:00:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    pinEmoji: '☕',
    categoryTags: { activity: ['coffee'], mood: ['peaceful'] },
    restaurantDetails: { wouldEatAgain: true },
  },
  {
    id: 'm-pch-bixby',
    tripId: T.highway,
    destinationId: D.bigsur,
    kind: 'sight',
    title: 'Bixby pullout — wind & salt',
    placeLabel: 'Big Sur, CA',
    lat: 36.3715,
    lng: -121.9016,
    visitedAt: '2024-10-02T17:20:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    pinEmoji: '🌊',
    categoryTags: { vibe: ['off the map'], moment: ['no plan, best plan'] },
  },
  {
    id: 'm-pch-la',
    tripId: T.highway,
    destinationId: D.la,
    kind: 'note',
    title: 'LA traffic truce — tacos anyway',
    placeLabel: 'East LA',
    lat: 34.05,
    lng: -118.25,
    visitedAt: '2024-10-04T20:00:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    categoryTags: { activity: ['food'], mood: ['electric'] },
  },
]

export type DemoPersistedState = {
  trips: Trip[]
  destinations: Destination[]
  memories: Memory[]
  friends: Friend[]
  tagCategories: TagCategory[]
  selectionLists: SelectionList[]
  selectedTripId: string | null
  uiSoundEnabled: boolean
}

export function getDemoPersistedState(): DemoPersistedState {
  return withTriplessInfrastructure({
    trips,
    destinations,
    memories,
    friends,
    tagCategories: cloneDefaultCategories(),
    selectionLists: cloneDefaultSelectionLists(),
    selectedTripId: T.spring,
    uiSoundEnabled: true,
  })
}

export function seedIfEmpty(): DemoPersistedState {
  return getDemoPersistedState()
}
