import type {
  Destination,
  Friend,
  Memory,
  SelectionList,
  TagCategory,
  Trip,
} from '../types'
import { withTriplessInfrastructure } from '../lib/tripless'
import { cloneDefaultCategories } from '../whimsy/tagLibrary'
import { cloneDefaultSelectionLists } from '../whimsy/selectionLists'

/** Stable ids (safe for load demo reset) */
const T = {
  spring: 'trip-spring-euro-asia',
  portugal: 'trip-portugal-weekend',
  hokkaido: 'trip-hokkaido-snow',
  nyc: 'trip-nyc-staycation',
  highway: 'trip-pch-slow',
  uk: 'trip-uk-autumn',
} as const

const D = {
  paris: 'dest-paris',
  tokyo: 'dest-tokyo',
  lisbon: 'dest-lisbon',
  porto: 'dest-porto',
  sapporo: 'dest-sapporo',
  niseko: 'dest-niseko',
  manhattan: 'dest-manhattan',
  brooklyn: 'dest-brooklyn',
  sf: 'dest-sf',
  bigsur: 'dest-bigsur',
  la: 'dest-la',
  london: 'dest-london',
  edinburgh: 'dest-edinburgh',
  sb: 'dest-sb',
  morro: 'dest-morro',
} as const

const trips: Trip[] = [
  { id: T.spring, name: 'Spring Paris to Tokyo' },
  { id: T.portugal, name: 'Portugal long weekend' },
  { id: T.hokkaido, name: 'Hokkaido snow week' },
  { id: T.nyc, name: 'NYC staycation' },
  { id: T.highway, name: 'Pacific Coast slow roll' },
  { id: T.uk, name: 'UK autumn week' },
]

const destinations: Destination[] = [
  { id: D.paris, tripId: T.spring, name: 'Paris' },
  { id: D.tokyo, tripId: T.spring, name: 'Tokyo' },
  { id: D.lisbon, tripId: T.portugal, name: 'Lisbon' },
  { id: D.porto, tripId: T.portugal, name: 'Porto' },
  { id: D.sapporo, tripId: T.hokkaido, name: 'Sapporo' },
  { id: D.niseko, tripId: T.hokkaido, name: 'Niseko' },
  { id: D.manhattan, tripId: T.nyc, name: 'Manhattan' },
  { id: D.brooklyn, tripId: T.nyc, name: 'Brooklyn' },
  { id: D.sf, tripId: T.highway, name: 'San Francisco' },
  { id: D.bigsur, tripId: T.highway, name: 'Big Sur' },
  { id: D.la, tripId: T.highway, name: 'Los Angeles' },
  { id: D.sb, tripId: T.highway, name: 'Santa Barbara' },
  { id: D.morro, tripId: T.highway, name: 'Morro Bay' },
  { id: D.london, tripId: T.uk, name: 'London' },
  { id: D.edinburgh, tripId: T.uk, name: 'Edinburgh' },
]

const friends: Friend[] = [
  { id: 'f-alex', name: 'Alex', color: '#2563eb' },
  { id: 'f-sam', name: 'Sam', color: '#059669' },
  { id: 'f-morgan', name: 'Morgan', color: '#d97706' },
  { id: 'f-jules', name: 'Jules', color: '#dc2626' },
  { id: 'f-riley', name: 'Riley', color: '#7c3aed' },
  { id: 'f-nina', name: 'Nina', color: '#db2777' },
]

const memories: Memory[] = [
  /* Spring */
  {
    id: 'm-spring-cdg',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'flight',
    title: 'CDG landing, half awake',
    placeLabel: 'Charles de Gaulle Airport, Paris, France',
    lat: 49.0097,
    lng: 2.5479,
    visitedAt: '2026-03-10T14:00:00.000Z',
    pinEmoji: '✈️',
    countryCode: 'FR',
    adminRegion: 'Île-de-France',
    categoryTags: {
      vibe: ['big city buzz'],
      mood: ['electric'],
      moment: ['first time'],
      activity: ['transit'],
    },
    friendIds: ['f-alex'],
    flightDetails: {
      fromCode: 'JFK',
      toCode: 'CDG',
      fromLat: 40.6413,
      fromLng: -73.7781,
      toLat: 49.0097,
      toLng: 2.5479,
      durationMinutes: 420,
      airline: 'Air France',
      aircraftType: 'B777-300ER',
      cabinClass: 'business',
    },
  },
  {
    id: 'm-spring-bistro',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'restaurant',
    title: 'Dinner near the river',
    placeLabel: '7th arrondissement, Paris',
    lat: 48.8584,
    lng: 2.2945,
    visitedAt: '2026-03-11T19:30:00.000Z',
    pinEmoji: '🍽️',
    countryCode: 'FR',
    adminRegion: 'Île-de-France',
    categoryTags: {
      vibe: ['golden hour'],
      mood: ['cozy'],
      activity: ['food'],
    },
    friendIds: ['f-alex', 'f-sam'],
    selectionListValues: { cuisine: 'French' },
    restaurantDetails: {
      wouldEatAgain: true,
      rating: 5,
      cuisine: 'French',
      venueStyle: 'Bistro',
    },
    body: 'Steak frites. Probably too much wine.',
  },
  {
    id: 'm-spring-hotel',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'hotel',
    title: 'Left Bank hotel',
    lat: 48.85,
    lng: 2.34,
    visitedAt: '2026-03-11T15:00:00.000Z',
    countryCode: 'FR',
    categoryTags: { mood: ['peaceful'], activity: ['transit'] },
    hotelDetails: {
      checkIn: '2026-03-11',
      checkOut: '2026-03-14',
      nights: 3,
      brand: 'Boutique Left Bank',
    },
    body: 'Small elevator. Big windows onto the courtyard.',
  },
  {
    id: 'm-spring-louvre',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'sight',
    title: 'Louvre half day',
    placeLabel: 'Musée du Louvre',
    lat: 48.8606,
    lng: 2.3376,
    visitedAt: '2026-03-12T11:00:00.000Z',
    pinEmoji: '🏛️',
    countryCode: 'FR',
    categoryTags: { activity: ['museum'], moment: ['tiny joy'] },
    body: 'Only did Denon. Need a whole day next time.',
    sightDetails: { venueType: 'Museum' },
  },
  {
    id: 'm-spring-tokyo-flight',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'flight',
    title: 'Red eye into Haneda',
    lat: 35.5494,
    lng: 139.7798,
    visitedAt: '2026-03-15T06:30:00.000Z',
    countryCode: 'JP',
    adminRegion: 'Tokyo',
    categoryTags: { vibe: ['big city buzz'], activity: ['transit'] },
    body: 'Slept badly. Landed into gray sky anyway.',
    flightDetails: {
      fromCode: 'CDG',
      toCode: 'HND',
      fromLat: 49.0097,
      fromLng: 2.5479,
      toLat: 35.5494,
      toLng: 139.7798,
      durationMinutes: 840,
    },
  },
  {
    id: 'm-spring-ramen',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'restaurant',
    title: 'Midnight ramen counter',
    placeLabel: 'Shibuya, Tokyo',
    lat: 35.69,
    lng: 139.7,
    visitedAt: '2026-03-16T00:20:00.000Z',
    pinEmoji: '🍜',
    countryCode: 'JP',
    categoryTags: { vibe: ['locals only'], mood: ['giddy'], activity: ['food'] },
    restaurantDetails: { wouldEatAgain: true },
    body: 'Counter seat. Broth too hot to sip at first.',
  },
  /* Same calendar day other years (time machine / "this time last year") */
  {
    id: 'm-echo-2024-0330',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'note',
    title: 'Rainy Tuesday notes (2024)',
    lat: 38.7223,
    lng: -9.1393,
    visitedAt: '2024-03-30T11:00:00.000Z',
    countryCode: 'PT',
    body: 'Grey Tuesday. Tried to journal more, mostly people-watched.',
  },
  {
    id: 'm-echo-2025-0330',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'note',
    title: 'Coffee between deadlines (2025)',
    lat: 40.7589,
    lng: -73.9851,
    visitedAt: '2025-03-30T15:30:00.000Z',
    countryCode: 'US',
    adminRegion: 'New York',
    categoryTags: { activity: ['coffee'], mood: ['peaceful'] },
    body: 'March 30 again.',
  },
  {
    id: 'm-echo-2026-0330',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'sight',
    title: 'Early cherry buds (2026)',
    lat: 35.7148,
    lng: 139.7967,
    visitedAt: '2026-03-30T08:00:00.000Z',
    countryCode: 'JP',
    pinEmoji: '🌸',
    categoryTags: { moment: ['tiny joy'], vibe: ['golden hour'] },
    body: 'Buds only. Still a crowd on the path.',
  },
  /* Portugal */
  {
    id: 'm-ptl-tram',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'sight',
    title: 'Alfama and the 28 tram',
    placeLabel: 'Alfama, Lisbon',
    lat: 38.7125,
    lng: -9.1333,
    visitedAt: '2025-11-08T10:00:00.000Z',
    countryCode: 'PT',
    adminRegion: 'Lisbon',
    pinEmoji: '🚂',
    categoryTags: { vibe: ['golden hour'], activity: ['transit'] },
    friendIds: ['f-morgan'],
    body: 'Packed tram. Light was nice though.',
  },
  {
    id: 'm-ptl-pasteis',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'restaurant',
    title: 'Pastéis stop',
    lat: 38.6979,
    lng: -9.2034,
    visitedAt: '2025-11-08T08:30:00.000Z',
    countryCode: 'PT',
    categoryTags: { activity: ['food', 'coffee'], mood: ['giddy'] },
    restaurantDetails: { wouldEatAgain: true, rating: 5 },
    body: 'Still warm. Cinnamon on my sleeve.',
  },
  {
    id: 'm-ptl-porto',
    tripId: T.portugal,
    destinationId: D.porto,
    kind: 'note',
    title: 'Grey afternoon by the river',
    placeLabel: 'Ribeira, Porto',
    lat: 41.14,
    lng: -8.61,
    visitedAt: '2025-11-09T16:00:00.000Z',
    countryCode: 'PT',
    categoryTags: { mood: ['peaceful'], vibe: ['off the map'] },
    body: 'Sat on the wall for an hour. No regrets.',
  },
  /* Hokkaido */
  {
    id: 'm-hok-sapporo',
    tripId: T.hokkaido,
    destinationId: D.sapporo,
    kind: 'restaurant',
    title: 'Soup curry after the flight',
    lat: 43.0618,
    lng: 141.3545,
    visitedAt: '2025-02-03T19:00:00.000Z',
    countryCode: 'JP',
    adminRegion: 'Hokkaido',
    pinEmoji: '🍜',
    categoryTags: { activity: ['food'], mood: ['cozy'] },
    restaurantDetails: { wouldEatAgain: true },
    friendIds: ['f-jules', 'f-sam'],
    body: 'Steam on my glasses the whole meal.',
  },
  {
    id: 'm-hok-niseko',
    tripId: T.hokkaido,
    destinationId: D.niseko,
    kind: 'sight',
    title: 'Deep snow in Niseko',
    lat: 42.8053,
    lng: 140.6876,
    visitedAt: '2025-02-05T09:00:00.000Z',
    pinEmoji: '🎿',
    countryCode: 'JP',
    categoryTags: { activity: ['hike'], moment: ['first time'] },
    body: 'Kept skiing until my legs quit.',
  },
  /* NYC */
  {
    id: 'm-nyc-bagel',
    tripId: T.nyc,
    destinationId: D.brooklyn,
    kind: 'restaurant',
    title: 'Bagels on a park bench',
    placeLabel: 'Prospect Park, Brooklyn',
    lat: 40.66,
    lng: -73.97,
    visitedAt: '2025-09-14T06:45:00.000Z',
    countryCode: 'US',
    adminRegion: 'New York',
    pinEmoji: '🥐',
    categoryTags: { vibe: ['golden hour'], activity: ['food', 'coffee'] },
    restaurantDetails: { wouldEatAgain: true },
  },
  {
    id: 'm-nyc-met',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'sight',
    title: 'Met rooftop closed, Greek wing instead',
    lat: 40.7794,
    lng: -73.9632,
    visitedAt: '2025-09-15T13:00:00.000Z',
    countryCode: 'US',
    adminRegion: 'New York',
    categoryTags: { activity: ['museum'] },
    friendIds: ['f-alex'],
    body: 'Greek wing was empty. Rooftop closed for wind.',
  },
  {
    id: 'm-nyc-hotel',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'hotel',
    title: 'Small room, big windows',
    lat: 40.758,
    lng: -73.9855,
    visitedAt: '2025-09-14T15:00:00.000Z',
    countryCode: 'US',
    hotelDetails: { checkIn: '2025-09-14', checkOut: '2025-09-17' },
  },
  /* PCH */
  {
    id: 'm-pch-sf',
    tripId: T.highway,
    destinationId: D.sf,
    kind: 'restaurant',
    title: 'Coffee in the Mission before the bridge',
    placeLabel: 'Mission, San Francisco',
    lat: 37.767,
    lng: -122.421,
    visitedAt: '2024-10-01T09:00:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    pinEmoji: '☕',
    categoryTags: { activity: ['coffee'], mood: ['peaceful'] },
    restaurantDetails: { wouldEatAgain: true },
  },
  {
    id: 'm-pch-bixby',
    tripId: T.highway,
    destinationId: D.bigsur,
    kind: 'sight',
    title: 'Bixby pullout, windy',
    placeLabel: 'Big Sur, CA',
    lat: 36.3715,
    lng: -121.9016,
    visitedAt: '2024-10-02T17:20:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    pinEmoji: '🌊',
    categoryTags: { vibe: ['off the map'], moment: ['no plan, best plan'] },
    body: 'Cold wind. Everyone had the same pullout shot.',
  },
  {
    id: 'm-pch-la',
    tripId: T.highway,
    destinationId: D.la,
    kind: 'note',
    title: 'Terrible traffic, good tacos',
    placeLabel: 'East LA',
    lat: 34.05,
    lng: -118.25,
    visitedAt: '2024-10-04T20:00:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    categoryTags: { activity: ['food'], mood: ['electric'] },
    body: 'Two hours on the 405. Tacos were worth it.',
  },
  /* Spring — extra Paris / Tokyo beats */
  {
    id: 'm-spring-montmartre',
    tripId: T.spring,
    destinationId: D.paris,
    kind: 'sight',
    title: 'Montmartre stairs in the rain',
    placeLabel: 'Montmartre, Paris',
    lat: 48.8867,
    lng: 2.3431,
    visitedAt: '2026-03-13T11:30:00.000Z',
    pinEmoji: '🎨',
    countryCode: 'FR',
    categoryTags: { vibe: ['locals only'], activity: ['hike'] },
    friendIds: ['f-sam'],
    sightDetails: { venueType: 'Neighborhood' },
    body: 'Paint ran in the rain on the steps.',
  },
  {
    id: 'm-spring-shinjuku-hotel',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'hotel',
    title: 'Shinjuku tower room',
    placeLabel: 'Shinjuku, Tokyo',
    lat: 35.6938,
    lng: 139.7014,
    visitedAt: '2026-03-17T16:00:00.000Z',
    countryCode: 'JP',
    hotelDetails: {
      checkIn: '2026-03-17',
      checkOut: '2026-03-20',
      nights: 3,
      brand: 'City tower',
      stars: 4,
    },
    body: 'High floor. Could hear the trains until 1.',
  },
  {
    id: 'm-spring-yoyogi',
    tripId: T.spring,
    destinationId: D.tokyo,
    kind: 'sight',
    title: 'Yoyogi Park loop',
    placeLabel: 'Shibuya, Tokyo',
    lat: 35.6717,
    lng: 139.6949,
    visitedAt: '2026-03-18T09:15:00.000Z',
    pinEmoji: '🌳',
    countryCode: 'JP',
    categoryTags: { mood: ['peaceful'], activity: ['hike'] },
    body: 'Jet lag walk. Crowds thinned out by the pond.',
    sightDetails: { venueType: 'Park' },
  },
  /* Portugal — coast + night */
  {
    id: 'm-ptl-cascais',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'sight',
    title: 'Cascais boardwalk',
    placeLabel: 'Cascais, Portugal',
    lat: 38.6979,
    lng: -9.4215,
    visitedAt: '2025-11-07T14:20:00.000Z',
    countryCode: 'PT',
    pinEmoji: '🌊',
    categoryTags: { vibe: ['golden hour'], moment: ['tiny joy'] },
    friendIds: ['f-morgan', 'f-nina'],
  },
  {
    id: 'm-ptl-fado',
    tripId: T.portugal,
    destinationId: D.lisbon,
    kind: 'restaurant',
    title: 'Fado house, tiny tables',
    placeLabel: 'Alfama, Lisbon',
    lat: 38.712,
    lng: -9.131,
    visitedAt: '2025-11-09T21:00:00.000Z',
    countryCode: 'PT',
    pinEmoji: '🎵',
    categoryTags: { mood: ['cozy'], activity: ['food'] },
    restaurantDetails: {
      wouldEatAgain: true,
      rating: 4,
      cuisine: 'Portuguese',
      venueStyle: 'Tavern',
    },
    body: 'Singer two feet away. Olive oil cake after.',
  },
  /* Hokkaido — canal + ryokan */
  {
    id: 'm-hok-otaru',
    tripId: T.hokkaido,
    destinationId: D.sapporo,
    kind: 'sight',
    title: 'Otaru canal walk',
    placeLabel: 'Otaru, Hokkaido',
    lat: 43.1907,
    lng: 140.9947,
    visitedAt: '2025-02-04T13:00:00.000Z',
    countryCode: 'JP',
    pinEmoji: '🏮',
    categoryTags: { vibe: ['off the map'], activity: ['coffee'] },
    friendIds: ['f-jules'],
    sightDetails: { venueType: 'Historic quarter' },
  },
  {
    id: 'm-hok-onsen-hotel',
    tripId: T.hokkaido,
    destinationId: D.niseko,
    kind: 'hotel',
    title: 'Ryokan with mountain view',
    placeLabel: 'Niseko, Hokkaido',
    lat: 42.804,
    lng: 140.687,
    visitedAt: '2025-02-06T15:00:00.000Z',
    countryCode: 'JP',
    hotelDetails: {
      checkIn: '2025-02-06',
      checkOut: '2025-02-08',
      nights: 2,
      brand: 'Onsen ryokan',
      stars: 4,
    },
  },
  /* NYC — skyline walks + music */
  {
    id: 'm-nyc-high-line',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'sight',
    title: 'High Line at blue hour',
    placeLabel: 'Chelsea, Manhattan',
    lat: 40.748,
    lng: -74.0048,
    visitedAt: '2025-09-15T18:40:00.000Z',
    countryCode: 'US',
    pinEmoji: '🌆',
    categoryTags: { vibe: ['golden hour'], activity: ['hike'] },
    sightDetails: { venueType: 'Park' },
  },
  {
    id: 'm-nyc-jazz',
    tripId: T.nyc,
    destinationId: D.manhattan,
    kind: 'restaurant',
    title: 'Late set in the Village',
    placeLabel: 'Greenwich Village, Manhattan',
    lat: 40.7314,
    lng: -74.0025,
    visitedAt: '2025-09-16T22:30:00.000Z',
    countryCode: 'US',
    pinEmoji: '🎷',
    categoryTags: { mood: ['electric'], activity: ['food'] },
    friendIds: ['f-alex', 'f-riley'],
    restaurantDetails: {
      wouldEatAgain: true,
      rating: 5,
      venueStyle: 'Club',
    },
  },
  /* PCH — more pullouts */
  {
    id: 'm-pch-carmel',
    tripId: T.highway,
    destinationId: D.bigsur,
    kind: 'note',
    title: 'Foggy Carmel morning',
    placeLabel: 'Carmel-by-the-Sea, CA',
    lat: 36.5552,
    lng: -121.9233,
    visitedAt: '2024-10-02T08:10:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    categoryTags: { mood: ['peaceful'], vibe: ['off the map'] },
    body: 'Coffee then tide pools. Forgot gloves.',
  },
  {
    id: 'm-pch-santa-barbara',
    tripId: T.highway,
    destinationId: D.sb,
    kind: 'restaurant',
    title: 'Breakfast burrito on the pier',
    placeLabel: 'Santa Barbara, CA',
    lat: 34.4089,
    lng: -119.6933,
    visitedAt: '2024-10-03T09:30:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    pinEmoji: '🌯',
    categoryTags: { activity: ['food'], vibe: ['golden hour'] },
    restaurantDetails: { wouldEatAgain: true, rating: 4 },
  },
  {
    id: 'm-pch-morro',
    tripId: T.highway,
    destinationId: D.morro,
    kind: 'sight',
    title: 'Morro Rock from the beach',
    placeLabel: 'Morro Bay, CA',
    lat: 35.3658,
    lng: -120.8499,
    visitedAt: '2024-10-03T16:45:00.000Z',
    countryCode: 'US',
    adminRegion: 'California',
    pinEmoji: '🪨',
    categoryTags: { moment: ['no plan, best plan'] },
    sightDetails: { venueType: 'Viewpoint' },
  },
  /* UK — London → Edinburgh */
  {
    id: 'm-uk-iad-lhr',
    tripId: T.uk,
    destinationId: D.london,
    kind: 'flight',
    title: 'Red-eye into Heathrow',
    placeLabel: 'London Heathrow (LHR)',
    lat: 51.471,
    lng: -0.4543,
    visitedAt: '2026-10-02T07:05:00.000Z',
    pinEmoji: '✈️',
    countryCode: 'GB',
    adminRegion: 'England',
    categoryTags: { activity: ['transit'], mood: ['peaceful'] },
    friendIds: ['f-riley'],
    flightDetails: {
      fromCode: 'IAD',
      toCode: 'LHR',
      fromLat: 38.9531,
      fromLng: -77.4565,
      toLat: 51.471,
      toLng: -0.4543,
      durationMinutes: 465,
      airline: 'British Airways',
      aircraftType: 'A350-1000',
      cabinClass: 'economy',
    },
  },
  {
    id: 'm-uk-chips-pub',
    tripId: T.uk,
    destinationId: D.london,
    kind: 'restaurant',
    title: 'Fish and chips, first night',
    placeLabel: 'Marylebone, London',
    lat: 51.5225,
    lng: -0.1574,
    visitedAt: '2026-10-02T19:30:00.000Z',
    countryCode: 'GB',
    pinEmoji: '🍟',
    categoryTags: { activity: ['food'], mood: ['cozy'] },
    restaurantDetails: {
      wouldEatAgain: true,
      rating: 4,
      cuisine: 'British',
      venueStyle: 'Pub',
    },
  },
  {
    id: 'm-uk-british-museum',
    tripId: T.uk,
    destinationId: D.london,
    kind: 'sight',
    title: 'British Museum, half a day',
    placeLabel: 'Bloomsbury, London',
    lat: 51.5194,
    lng: -0.127,
    visitedAt: '2026-10-03T10:00:00.000Z',
    countryCode: 'GB',
    pinEmoji: '🏛️',
    categoryTags: { activity: ['museum'] },
    friendIds: ['f-nina', 'f-riley'],
    sightDetails: { venueType: 'Museum' },
    body: 'Rosetta was busy. Great Court was not.',
  },
  {
    id: 'm-uk-hotel-london',
    tripId: T.uk,
    destinationId: D.london,
    kind: 'hotel',
    title: 'Quiet block near the park',
    placeLabel: 'Marylebone, London',
    lat: 51.5208,
    lng: -0.155,
    visitedAt: '2026-10-02T14:00:00.000Z',
    countryCode: 'GB',
    hotelDetails: {
      checkIn: '2026-10-02',
      checkOut: '2026-10-05',
      nights: 3,
      brand: 'Townhouse hotel',
      stars: 4,
    },
  },
  {
    id: 'm-uk-notes-kings-cross',
    tripId: T.uk,
    destinationId: D.london,
    kind: 'note',
    title: 'Train north, notes on the seat tray',
    placeLabel: "King's Cross, London",
    lat: 51.532,
    lng: -0.1233,
    visitedAt: '2026-10-05T09:20:00.000Z',
    countryCode: 'GB',
    categoryTags: { activity: ['transit'], mood: ['peaceful'] },
    body: 'Reserved seat, wrong side for sun. Still good.',
  },
  {
    id: 'm-uk-edinburgh-castle',
    tripId: T.uk,
    destinationId: D.edinburgh,
    kind: 'sight',
    title: 'Castle esplanade wind',
    placeLabel: 'Edinburgh Castle',
    lat: 55.9486,
    lng: -3.1999,
    visitedAt: '2026-10-05T15:30:00.000Z',
    countryCode: 'GB',
    adminRegion: 'Scotland',
    pinEmoji: '🏰',
    categoryTags: { activity: ['museum'], moment: ['first time'] },
    sightDetails: { venueType: 'Historic site' },
    body: 'Wind on the esplanade. Hard to hold the phone steady.',
  },
  {
    id: 'm-uk-whisky-bar',
    tripId: T.uk,
    destinationId: D.edinburgh,
    kind: 'restaurant',
    title: 'Whisky flight on Grassmarket',
    placeLabel: 'Old Town, Edinburgh',
    lat: 55.9473,
    lng: -3.1958,
    visitedAt: '2026-10-06T20:15:00.000Z',
    countryCode: 'GB',
    pinEmoji: '🥃',
    categoryTags: { mood: ['cozy'], activity: ['food'] },
    friendIds: ['f-sam', 'f-riley'],
    restaurantDetails: {
      wouldEatAgain: true,
      rating: 5,
      venueStyle: 'Bar',
    },
  },
  {
    id: 'm-uk-calton-hill',
    tripId: T.uk,
    destinationId: D.edinburgh,
    kind: 'sight',
    title: 'Calton Hill at last light',
    placeLabel: 'Calton Hill, Edinburgh',
    lat: 55.9544,
    lng: -3.1828,
    visitedAt: '2026-10-07T18:50:00.000Z',
    countryCode: 'GB',
    pinEmoji: '🌅',
    categoryTags: { vibe: ['golden hour'], moment: ['tiny joy'] },
    sightDetails: { venueType: 'Viewpoint' },
  },
]

export type DemoPersistedState = {
  trips: Trip[]
  destinations: Destination[]
  memories: Memory[]
  friends: Friend[]
  tagCategories: TagCategory[]
  selectionLists: SelectionList[]
  selectedTripId: string | null
  uiSoundEnabled: boolean
}

export function getDemoPersistedState(): DemoPersistedState {
  return withTriplessInfrastructure({
    trips,
    destinations,
    memories,
    friends,
    tagCategories: cloneDefaultCategories(),
    selectionLists: cloneDefaultSelectionLists(),
    selectedTripId: T.spring,
    uiSoundEnabled: true,
  })
}

export function seedIfEmpty(): DemoPersistedState {
  return getDemoPersistedState()
}
